site_name: My Docs
nav:
  - Home: index.md
  - Features:
    - Add Animal: features/add_animal.md
    - Consult Animal Profile: features/consult_animal_profile.md
    - Add Pet Picture: features/add_pet_picture.md

theme:
  name: material

plugins:
  - gherkin-plugin:
      show_results: true
      tests_root_path: "./tests_e2e"
      messages_path: "./tests_e2e/report/gherkin_messages.ndjson"

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

